---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: rameshkumarverma/simple-chat-websocket:latest
        ports:
        - containerPort: 6969   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
  - protocol: TCP
    port: 6969             # Expose port 80
    targetPort: 6969
  type: LoadBalancer
